name: Check MPL license headers

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  check_headers:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install addlicense
        run: go install github.com/google/addlicense@latest
      - name: Check headers
        run: $HOME/go/bin/addlicense -check -l mpl *.rs
